# Usage:
#
#     source-file dotfiles/.tmux.conf
#     ...
#     source-file dotfiles/.tmux-plugins.conf

set-option -g history-limit 1000000

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Mouse
set -g mouse on

# Clipboard
set -g set-clipboard on


##########################################################################
# True-color support in alacritty and ssh sessions
##########################################################################
set-option -ga terminal-overrides ",alacritty:RGB"
set-option -ga terminal-overrides ",screen:RGB"
set-option -ga terminal-overrides ",xterm:RGB"


##########################################################################
# Prefix
##########################################################################
# Allows us to use <prefix> <command> to send commands to a TMUX session inside
# another TMUX session
bind-key a send-prefix


##########################################################################
# Status line
##########################################################################
set -g status-bg black
set -g status-fg white
set -g status-left-length 19
set -g status-left "#{prefix_highlight}#[bg=green]#[fg=white]#h"
set -g status-right "#{cpu_bg_color}CPU #{cpu_percentage}"
# set -g status-right "#[bg=green]U #{upload_speed} | D #{download_speed} | #{cpu_bg_color}CPU #{cpu_percentage}"

# Show copy mode prefix in status line
set -g @prefix_highlight_show_copy_mode 'on'

# Highlight active window
set-window-option -g window-status-current-style bg=red


##########################################################################
# Vim-style copy+paste
##########################################################################
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind P paste-buffer
